name: Render wiki
description: 🚀 Action to create wiki markdown 

inputs:
  wikiPath:
    description:
      Path of the folder in which to create the wiki
    default: wiki

  wikiConfig:
    description:
      Wiki config yaml path
    default: wiki.yaml

outputs:
  wikiHomePath:
    description:
      Path to home markdown
    value: ${{ steps.main.outputs.wikiHomePath }}

runs:
  using: composite
  steps:
    - name: 'Setup yq'
      uses: dcarbone/install-yq-action@v1.1.1

    - name: 'Setup jq'
      uses: dcarbone/install-jq-action@v2.1.0

    - name: 'Audit tools'
      shell: bash
      run: |
        which jq
        jq --version
        which yq
        yq --version
        which awk
        awk -V

    - id: post
      shell: bash
      run: bash "$GITHUB_ACTION_PATH/render-wiki.sh"
      env:
        INPUT_WIKI_PATH: ${{ inputs.wikiPath }}
        INPUT_WIKI_CONFIG: ${{ inputs.wikiConfig }}
