wiki:
  home:
    title: RenderWiki wiki
    render:
      - Render wiki action is a simple mechanism for rendering markdown and other information in a workflow
      - index: page index
      - |
        !\u005BMade with RenderWiki\u005D(https://img.shields.io/badge/Made_with-RenderWiki-blue)

  pages:
    - title: Hello World
      render: |
        ## Hello

        World
        > Everyone

        ```json
        { hello: "world" }
        ```

    - title: About Render Wiki 
      render:
        - This is about the render-wiki action
        - "Created on" : date
