name: Render Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md
      - version.svg

jobs:
  renderTest:
    name: Verify wiki generation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action code
        uses: actions/checkout@v4

      - name: Invoke render-wiki action
        id: renderTest
        uses: ./
        with:
          wikiPath: testWiki
          wikiConfig: ./test/wiki-config.yaml

      - name: Verify wiki home exists
        shell: bash
        run: |
          [ ! -z "$OUTPUT_HOME_PATH" ] &&
          [ -f "$OUTPUT_HOME_PATH" ] &&
          echo "Home is OK: $OUTPUT_HOME_PATH" ||
          (echo "Home creation failed" && exit 1)
        env:
          OUTPUT_HOME_PATH: ${{ steps.renderTest.outputs.wikiHomePath }}
